### ISSUE TITLE
Collection does not display

### ISSUE THREAD

**Issue by bentley** [standardebooks/charles-dickens_little-dorrit#2]
Despite d8dfc776584c6f3604da51ae6a3844f33318fb98, *Great Books of the Western World* doesn’t show up on [the Little Dorrit page](https://standardebooks.org/ebooks/charles-dickens/little-dorrit), nor does Little Dorrit show up in [the collection’s own page](https://standardebooks.org/collections/encyclopaedia-britannicas-great-books-of-the-western-world). I haven’t figured out why.

**Comment by acabal** [comment]
It looks like  that commit introduced several invisible characters, U+000A U+FFFC U+0009 U+0009, that broke the XML. Maybe you copied from the wrong place? In any case this should be fixed now.

**Comment by bentley** [comment]
That’ll teach me to attempt simple commits from within the GitHub web interface. The CLI has never let me down…
